# **TASK-3 by XGBoost Model and AdaBoost Model**
This file contains task-3 operations for problem statement-2(referenced from readme) performed by using XGBoost model and AdaBoost model as mentioned in the question.


# DATA PREPROCESSING AND DATA TRANSFORMATION

## Importing all the needed libraries


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

## Creating a dataframe for smoking and drinking dataset

In [ ]:
# df = pd.read_csv("/content/drive/MyDrive/DATASET/smoking_driking_dataset_Ver01.csv")
df=pd.read_csv('D:\Mtech\Sem 1\DATA MINING\CP2 Project\smoking_driking_dataset_Ver01.csv')

In [ ]:
df

sex  age  height  weight  waistline  sight_left  sight_right  \
0         Male   35     170      75       90.0         1.0          1.0   
1         Male   30     180      80       89.0         0.9          1.2   
2         Male   40     165      75       91.0         1.2          1.5   
3         Male   50     175      80       91.0         1.5          1.2   
4         Male   50     165      60       80.0         1.0          1.2   
...        ...  ...     ...     ...        ...         ...          ...   
991341    Male   45     175      80       92.1         1.5          1.5   
991342    Male   35     170      75       86.0         1.0          1.5   
991343  Female   40     155      50       68.0         1.0          0.7   
991344    Male   25     175      60       72.0         1.5          1.0   
991345    Male   50     160      70       90.5         1.0          1.5   

        hear_left  hear_right  SBP  ...  LDL_chole  triglyceride  hemoglobin  \
0               1           1  120  ...        126            92        17.1   
1               1           1  130  ...        148           121        15.8   
2               1           1  120  ...         74           104        15.8   
3               1           1  145  ...        104           106        17.6   
4               1           1  138  ...        117           104        13.8   
...           ...         ...  ...  ...        ...           ...         ...   
991341          1           1  114  ...        125           132        15.0   
991342          1           1  119  ...         84            45        15.8   
991343          1           1  110  ...         77           157        14.3   
991344          1           1  119  ...         73            53        14.5   
991345          1           1  133  ...        153           163        15.8   

        urine_protein  serum_creatinine  SGOT_AST  SGOT_ALT  gamma_GTP  \
0                   1               1.0        21        35         40   
1                   1               0.9        20        36         27   
2                   1               0.9        47        32         68   
3                   1               1.1        29        34         18   
4                   1               0.8        19        12         25   
...               ...               ...       ...       ...        ...   
991341              1               1.0        26        36         27   
991342              1               1.1        14        17         15   
991343              1               0.8        30        27         17   
991344              1               0.8        21        14         17   
991345              1               0.9        24        43         36   

        SMK_stat_type_cd  DRK_YN  
0                      1       Y  
1                      3       N  
2                      1       N  
3                      1       N  
4                      1       N  
...                  ...     ...  
991341                 1       N  
991342                 1       N  
991343                 3       Y  
991344                 1       N  
991345                 3       Y  

[991346 rows x 24 columns]

In [ ]:
df.shape

(991346, 24)

In [ ]:
col =df.columns

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 991346 entries, 0 to 991345
Data columns (total 24 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   sex               991346 non-null  object 
 1   age               991346 non-null  int64  
 2   height            991346 non-null  int64  
 3   weight            991346 non-null  int64  
 4   waistline         991346 non-null  float64
 5   sight_left        991346 non-null  float64
 6   sight_right       991346 non-null  float64
 7   hear_left         991346 non-null  int64  
 8   hear_right        991346 non-null  int64  
 9   SBP               991346 non-null  int64  
 10  DBP               991346 non-null  int64  
 11  BLDS              991346 non-null  int64  
 12  tot_chole         991346 non-null  int64  
 13  HDL_chole         991346 non-null  int64  
 14  LDL_chole         991346 non-null  int64  
 15  triglyceride      991346 non-null  int64  
 16  hemoglobin        99

## Checking for null values

In [ ]:
df.isnull().sum()

sex                 0
age                 0
height              0
weight              0
waistline           0
sight_left          0
sight_right         0
hear_left           0
hear_right          0
SBP                 0
DBP                 0
BLDS                0
tot_chole           0
HDL_chole           0
LDL_chole           0
triglyceride        0
hemoglobin          0
urine_protein       0
serum_creatinine    0
SGOT_AST            0
SGOT_ALT            0
gamma_GTP           0
SMK_stat_type_cd    0
DRK_YN              0
dtype: int64

Also as observed in the EDA file there are **no unknown values** in this dataset and hence imputation is not required.

##Encoding


### Label Encoding
Here columns 'Sex',  'SMK_stat_type_cd',  'DRK_YN' have values with string data-type and will be label encoded.

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])
df["sex"].unique()

array([1, 0])

In [ ]:
df["DRK_YN"] = le.fit_transform(df["DRK_YN"])
df["DRK_YN"].unique()

array([1, 0])

In [ ]:
df

sex  age  height  weight  waistline  sight_left  sight_right  \
0         1   35     170      75       90.0         1.0          1.0   
1         1   30     180      80       89.0         0.9          1.2   
2         1   40     165      75       91.0         1.2          1.5   
3         1   50     175      80       91.0         1.5          1.2   
4         1   50     165      60       80.0         1.0          1.2   
...     ...  ...     ...     ...        ...         ...          ...   
991341    1   45     175      80       92.1         1.5          1.5   
991342    1   35     170      75       86.0         1.0          1.5   
991343    0   40     155      50       68.0         1.0          0.7   
991344    1   25     175      60       72.0         1.5          1.0   
991345    1   50     160      70       90.5         1.0          1.5   

        hear_left  hear_right  SBP  ...  LDL_chole  triglyceride  hemoglobin  \
0               1           1  120  ...        126            92        17.1   
1               1           1  130  ...        148           121        15.8   
2               1           1  120  ...         74           104        15.8   
3               1           1  145  ...        104           106        17.6   
4               1           1  138  ...        117           104        13.8   
...           ...         ...  ...  ...        ...           ...         ...   
991341          1           1  114  ...        125           132        15.0   
991342          1           1  119  ...         84            45        15.8   
991343          1           1  110  ...         77           157        14.3   
991344          1           1  119  ...         73            53        14.5   
991345          1           1  133  ...        153           163        15.8   

        urine_protein  serum_creatinine  SGOT_AST  SGOT_ALT  gamma_GTP  \
0                   1               1.0        21        35         40   
1                   1               0.9        20        36         27   
2                   1               0.9        47        32         68   
3                   1               1.1        29        34         18   
4                   1               0.8        19        12         25   
...               ...               ...       ...       ...        ...   
991341              1               1.0        26        36         27   
991342              1               1.1        14        17         15   
991343              1               0.8        30        27         17   
991344              1               0.8        21        14         17   
991345              1               0.9        24        43         36   

        SMK_stat_type_cd  DRK_YN  
0                      1       1  
1                      3       0  
2                      1       0  
3                      1       0  
4                      1       0  
...                  ...     ...  
991341                 1       0  
991342                 1       0  
991343                 3       1  
991344                 1       0  
991345                 3       1  

[991346 rows x 24 columns]

## Correlation Matrix

In [ ]:
df.corr()

sex       age    height    weight  waistline  \
sex               1.000000 -0.083225  0.722774  0.581707   0.344725   
age              -0.083225  1.000000 -0.398501 -0.195337   0.127170   
height            0.722774 -0.398501  1.000000  0.668823   0.263945   
weight            0.581707 -0.195337  0.668823  1.000000   0.637173   
waistline         0.344725  0.127170  0.263945  0.637173   1.000000   
sight_left        0.099016 -0.172096  0.139141  0.088901   0.004511   
sight_right       0.101522 -0.167684  0.138529  0.088707   0.006158   
hear_left         0.002926  0.203021 -0.081159 -0.044498   0.033224   
hear_right       -0.000751  0.198693 -0.082456 -0.045709   0.031012   
SBP               0.176245  0.265530  0.035030  0.250770   0.272323   
DBP               0.199202  0.108847  0.108780  0.277891   0.240890   
BLDS              0.118005  0.195796  0.021266  0.138587   0.175519   
tot_chole        -0.022444  0.011446 -0.023240  0.063238   0.063201   
HDL_chole        -0.256613 -0.104624 -0.148599 -0.287688  -0.253988   
LDL_chole        -0.005210  0.029497 -0.015450  0.067859   0.063416   
triglyceride      0.216283  0.043549  0.137611  0.283774   0.249436   
hemoglobin        0.669417 -0.173081  0.531898  0.499491   0.291730   
urine_protein     0.020184  0.041497  0.002298  0.029281   0.043132   
serum_creatinine  0.245956  0.022819  0.171256  0.153885   0.098421   
SGOT_AST          0.092943  0.059408  0.039203  0.099652   0.096858   
SGOT_ALT          0.196751 -0.020506  0.144842  0.276440   0.212267   
gamma_GTP         0.257229  0.017391  0.162340  0.221881   0.186988   
SMK_stat_type_cd  0.591004 -0.126031  0.467317  0.366499   0.205485   
DRK_YN            0.368726 -0.284587  0.374566  0.264282   0.092993   

                  sight_left  sight_right  hear_left  hear_right       SBP  \
sex                 0.099016     0.101522   0.002926   -0.000751  0.176245   
age                -0.172096    -0.167684   0.203021    0.198693  0.265530   
height              0.139141     0.138529  -0.081159   -0.082456  0.035030   
weight              0.088901     0.088707  -0.044498   -0.045709  0.250770   
waistline           0.004511     0.006158   0.033224    0.031012  0.272323   
sight_left          1.000000     0.307985  -0.039428   -0.040998 -0.035617   
sight_right         0.307985     1.000000  -0.040764   -0.038895 -0.033994   
hear_left          -0.039428    -0.040764   1.000000    0.536890  0.056065   
hear_right         -0.040998    -0.038895   0.536890    1.000000  0.057436   
SBP                -0.035617    -0.033994   0.056065    0.057436  1.000000   
DBP                -0.001209    -0.000568   0.006893    0.007524  0.741131   
BLDS               -0.034817    -0.036893   0.039776    0.040905  0.183141   
tot_chole           0.004371     0.003437  -0.024342   -0.022866  0.068557   
HDL_chole          -0.004224    -0.006259  -0.029464   -0.028046 -0.111772   
LDL_chole           0.003013     0.002155  -0.014621   -0.013438  0.033619   
triglyceride        0.010599     0.012265   0.002095    0.002155  0.186003   
hemoglobin          0.085896     0.086847  -0.036058   -0.036703  0.166530   
urine_protein      -0.010253    -0.010897   0.019754    0.018264  0.063518   
serum_creatinine    0.020309     0.021447   0.015254    0.012959  0.062605   
SGOT_AST           -0.005427    -0.004600   0.011283    0.010763  0.081478   
SGOT_ALT            0.018815     0.018920  -0.007907   -0.008687  0.117613   
gamma_GTP           0.013566     0.016491   0.002991    0.003548  0.161434   
SMK_stat_type_cd    0.064194     0.065051  -0.021245   -0.022330  0.084918   
DRK_YN              0.077379     0.074806  -0.058337   -0.058230  0.033149   

                  ...  LDL_chole  triglyceride  hemoglobin  urine_protein  \
sex               ...  -0.005210      0.216283    0.669417       0.020184   
age               ...   0.029497      0.043549   -0.173081       0.041497   
height            ...  -0.015450      0.137611    0.531898       

In [ ]:
df.columns

Index(['sex', 'age', 'height', 'weight', 'waistline', 'sight_left',
       'sight_right', 'hear_left', 'hear_right', 'SBP', 'DBP', 'BLDS',
       'tot_chole', 'HDL_chole', 'LDL_chole', 'triglyceride', 'hemoglobin',
       'urine_protein', 'serum_creatinine', 'SGOT_AST', 'SGOT_ALT',
       'gamma_GTP', 'SMK_stat_type_cd', 'DRK_YN'],
      dtype='object')

## Splitting Dataset

In [ ]:
k=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23]
X = df.iloc[:,k].values
y=df.iloc[:,22].values

In [ ]:
X.shape

(991346, 23)

In [ ]:
# y =y.reshape(len(y),1)
y = y.ravel()
y

array([1, 3, 1, ..., 3, 1, 3], dtype=int64)

## Train-Test Split and Scaling data by use of Standardization



Splitting our data into train and test datasets.
Here testing dataset contains 20% of all the data and training dataset contains the remaining 80%.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train,X_test,Y_train,Y_test= train_test_split(X,y,test_size=0.2,random_state=0)

sd = StandardScaler()
X_train = sd.fit_transform(X_train)
X_test = sd.transform(X_test)

X_train

array([[-1.06350214,  0.87347866, -0.77943715, ..., -0.14143111,
        -0.49798139, -0.99976046],
       [ 0.9402896 , -0.18412336,  1.37422935, ...,  0.12369009,
        -0.26038478,  1.0002396 ],
       [-1.06350214, -0.53665736,  0.2973961 , ..., -0.40655231,
        -0.53758082,  1.0002396 ],
       ...,
       [ 0.9402896 , -0.88919137,  1.37422935, ..., -0.44442677,
        -0.49798139, -0.99976046],
       [ 0.9402896 , -0.88919137,  0.83581273, ..., -0.70954797,
        -0.5177811 ,  1.0002396 ],
       [-1.06350214,  0.16841065, -0.77943715, ..., -0.17930557,
        -0.16138619, -0.99976046]])

In [ ]:
X_test

array([[-1.06350214,  0.87347866, -1.8562704 , ..., -0.44442677,
        -0.47818167, -0.99976046],
       [-1.06350214, -0.53665736, -0.24102052, ..., -0.55805014,
        -0.49798139, -0.99976046],
       [ 0.9402896 , -0.88919137,  1.37422935, ..., -0.55805014,
        -0.16138619,  1.0002396 ],
       ...,
       [-1.06350214,  0.16841065, -0.24102052, ..., -0.55805014,
        -0.53758082, -0.99976046],
       [-1.06350214,  0.16841065, -1.8562704 , ..., -0.5959246 ,
         0.13560958, -0.99976046],
       [ 0.9402896 ,  0.52094465,  0.83581273, ..., -0.29292894,
        -0.20098562,  1.0002396 ]])

# KNN MODEL BUILDING

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [ ]:
y_pred = knn.predict(X_test)


In [ ]:
from sklearn.metrics import accuracy_score,classification_report

accuracy_score(Y_test,y_pred)

0.6608816260654663

In [ ]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           1       0.77      0.86      0.81    120425
           2       0.38      0.36      0.37     35078
           3       0.49      0.36      0.42     42767

    accuracy                           0.66    198270
   macro avg       0.55      0.52      0.53    198270
weighted avg       0.64      0.66      0.65    198270



Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, precision_score,recall_score, f1_score

precision = precision_score(Y_test,y_pred, average="weighted")
precision

0.6412099644021204

In [ ]:
# recall
recall = recall_score(Y_test,y_pred, average="weighted")
recall

0.6608816260654663

In [ ]:
# F1 score
f1 =  f1_score(Y_test,y_pred, average="weighted")
f1

0.6475847242718191

Model Optimization

In [ ]:
param_grid = {
    'n_neighbors': [3,7],  # Varying the number of neighbors
    'weights': ['uniform', 'distance'],  # Different weight options
    'p': [1, 2]  # Minkowski distance parameter for power parameter
}

In [ ]:
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 7], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [ ]:
best_params = grid_search.best_params_
print("Best hyperparameters:", best_params)

Best hyperparameters: {'n_neighbors': 7, 'p': 1, 'weights': 'distance'}


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_best_param = KNeighborsClassifier(n_neighbors=7,p=1,weights='distance')

knn_best_param.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=7, p=1, weights='distance')

In [ ]:
y_pred_knn_best = knn_best_param.predict(X_test)


In [ ]:
from sklearn.metrics import accuracy_score,classification_report

accuracy_score(Y_test,y_pred_knn_best)

0.6705502597468099

LOGISTIC CLASSIFIER


In [ ]:
from sklearn.linear_model import LogisticRegression

lr_clf =LogisticRegression()

lr_clf.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
y_pred_LR = lr_clf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report

accuracy_score(Y_test,y_pred_LR)


0.6913703535582791

In [ ]:
print(classification_report(Y_test,y_pred_LR))

              precision    recall  f1-score   support

           1       0.82      0.83      0.83    120425
           2       0.45      0.32      0.37     35078
           3       0.50      0.59      0.54     42767

    accuracy                           0.69    198270
   macro avg       0.59      0.58      0.58    198270
weighted avg       0.69      0.69      0.69    198270



In [ ]:
from sklearn.metrics import confusion_matrix, precision_score,recall_score, f1_score

precision = precision_score(Y_test,y_pred, average="weighted")
precision

0.6412099644021204

In [ ]:
# recall
recall = recall_score(Y_test,y_pred, average="weighted")
recall

0.6608816260654663

In [ ]:
# F1 score
f1 =  f1_score(Y_test,y_pred, average="weighted")
f1

0.6475847242718191

Model Optimization

In [ ]:
param_grid = {
    'C': [0.01, 0.1,1,10]
}

In [ ]:
# # grid_search = GridSearchCV(lr_clf, param_grid, cv=5, scoring='accuracy')
# grid_search = GridSearchCV(lr_clf, param_grid, cv=5,scoring='accuracy')
# grid_search.fit(X_train, Y_train)

from sklearn.model_selection import GridSearchCV

grid_search_lr = GridSearchCV(lr_clf, param_grid, cv=5, scoring='accuracy')
grid_search_lr.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 10]}, scoring='accuracy')

In [ ]:
best_params = grid_search_lr.best_params_
print("Best hyperparameters:", best_params)

# Predict the classes for test set using the best model
best_logistic = grid_search_lr.best_estimator_
y_pred_LR_best = best_logistic.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(Y_test, y_pred_LR_best)
print(f"Accuracy of tuned Logistic Regression: {accuracy:.2f}")

Best hyperparameters: {'C': 0.01}
Accuracy of tuned Logistic Regression: 0.69
